/**
 * M2-06's loop protection, as pure functions: the inbound half says whether a
 * message was written by a machine, and the outbound half is the headers every
 * auto-reply carries so the machine on the other end can say the same of ours.
 *
 * Two auto-responders that answer each other forever is the failure this
 * prevents. RFC 3834 is the rule: never auto-reply to a message that carries
 * `Auto-Submitted` other than `no`, and mark every auto-reply
 * `Auto-Submitted: auto-replied`. `Precedence: bulk / list / junk` is the
 * older convention mailing lists and bulk senders still use, and
 * `noreply@` and `mailer-daemon@` are addresses nobody reads (DOMAIN-RULES
 * §4.3). The per-sender cap (`autoReplyHourlyCap`) is the backstop for a
 * sender that follows none of these.
 */

/** Header names as a parser hands them, in any case; values as they arrived. */
export type InboundHeaders = Readonly<Record<string, string | readonly string[] | undefined>>;

const MACHINE_PRECEDENCE = new Set(['bulk', 'list', 'junk']);

/** Local parts that belong to software rather than a person. */
const MACHINE_LOCAL_PART = /^(?:no[-_.]?reply|do[-_.]?not[-_.]?reply|mailer-daemon|postmaster)$/i;

const headerValue = (headers: InboundHeaders, name: string): string | undefined => {
  const wanted = name.toLowerCase();
  for (const [key, value] of Object.entries(headers)) {
    if (key.toLowerCase() === wanted) {
      const first = Array.isArray(value) ? value[0] : value;
      return typeof first === 'string' ? first.trim().toLowerCase() : undefined;
    }
  }

  return undefined;
};

/** Whether an address is one of the machine mailboxes above. */
export const isMachineAddress = (address: string): boolean => {
  const at = address.lastIndexOf('@');
  const local = at === -1 ? address : address.slice(0, at);

  return MACHINE_LOCAL_PART.test(local.trim());
};

/**
 * Whether an inbound message must never receive an auto-reply. The inbound
 * adapters (M2-02, M2-03) compute it when they parse a message and carry the
 * answer to the auto-responder; the same answer keeps such a message from
 * opening a ticket (DOMAIN-RULES §4.3).
 */
export const isAutoGeneratedEmail = ({
  from,
  headers,
}: {
  readonly from: string;
  readonly headers: InboundHeaders;
}): boolean => {
  const autoSubmitted = headerValue(headers, 'auto-submitted');
  if (autoSubmitted !== undefined && autoSubmitted !== '' && autoSubmitted !== 'no') {
    return true;
  }

  const precedence = headerValue(headers, 'precedence');
  if (precedence !== undefined && MACHINE_PRECEDENCE.has(precedence)) {
    return true;
  }

  return isMachineAddress(from);
};

/**
 * What every auto-reply carries. `X-Auto-Response-Suppress` is Exchange's own
 * spelling of the same request, which Outlook honours and RFC 3834 predates.
 */
export const AUTO_REPLY_HEADERS: Readonly<Record<string, string>> = Object.freeze({
  'Auto-Submitted': 'auto-replied',
  Precedence: 'bulk',
  'X-Auto-Response-Suppress': 'All',
});
