import { describe, expect, it } from 'vitest';
import { AUTO_REPLY_HEADERS, isAutoGeneratedEmail, isMachineAddress } from './loop-protection.js';

describe('isAutoGeneratedEmail', () => {
  const person = 'mona@example.com';

  it('lets an ordinary message through', () => {
    expect(isAutoGeneratedEmail({ from: person, headers: { subject: 'Hello' } })).toBe(false);
  });

  it('treats any Auto-Submitted other than no as a machine, in any header case', () => {
    expect(
      isAutoGeneratedEmail({ from: person, headers: { 'Auto-Submitted': 'auto-replied' } }),
    ).toBe(true);
    expect(
      isAutoGeneratedEmail({ from: person, headers: { 'auto-submitted': 'auto-generated' } }),
    ).toBe(true);
    expect(isAutoGeneratedEmail({ from: person, headers: { 'Auto-Submitted': 'No' } })).toBe(false);
  });

  it('treats Precedence bulk, list and junk as a machine', () => {
    for (const precedence of ['bulk', 'list', 'junk', ' Bulk ']) {
      expect(isAutoGeneratedEmail({ from: person, headers: { Precedence: precedence } })).toBe(
        true,
      );
    }
    expect(isAutoGeneratedEmail({ from: person, headers: { Precedence: 'first-class' } })).toBe(
      false,
    );
  });

  it('reads the first value when a parser hands a header over as a list', () => {
    expect(isAutoGeneratedEmail({ from: person, headers: { precedence: ['list', 'bulk'] } })).toBe(
      true,
    );
  });

  it('treats noreply and mailer-daemon senders as a machine', () => {
    expect(isAutoGeneratedEmail({ from: 'noreply@shop.example', headers: {} })).toBe(true);
    expect(isAutoGeneratedEmail({ from: 'MAILER-DAEMON@mx.example', headers: {} })).toBe(true);
  });
});

describe('isMachineAddress', () => {
  it('matches the spellings of no-reply and nothing else', () => {
    expect(isMachineAddress('no-reply@example.com')).toBe(true);
    expect(isMachineAddress('do_not_reply@example.com')).toBe(true);
    expect(isMachineAddress('postmaster@example.com')).toBe(true);
    expect(isMachineAddress('noreply-team@example.com')).toBe(false);
    expect(isMachineAddress('replyguy@example.com')).toBe(false);
  });
});

describe('AUTO_REPLY_HEADERS', () => {
  it('marks every auto-reply the way RFC 3834 asks', () => {
    expect(AUTO_REPLY_HEADERS['Auto-Submitted']).toBe('auto-replied');
    expect(AUTO_REPLY_HEADERS.Precedence).toBe('bulk');
  });
});
