export const PACKAGE_NAME = '@helpdock/schemas' as const;

export * from './auth.js';
export * from './brand.js';
export * from './contact.js';
export * from './custom-fields.js';
export * from './domain-check.js';
export * from './error.js';
export * from './health.js';
export * from './install.js';
export * from './media.js';
export * from './principal.js';
export * from './realtime.js';
export * from './retention.js';
export * from './staff.js';
export * from './system.js';
export * from './tags.js';
export * from './ticket.js';
export * from './ticket-templates.js';
export * from './ticketing.js';
