/**
 * Row-level security is the second of the four enforcement layers in
 * DOMAIN-RULES §1.3, and the only one that still holds when a query is written
 * by hand or a guard is forgotten. Every tenant table gets the same four
 * policies from {@link tenantPolicies}, so there is one shape to review and one
 * place to change it.
 */

/** The `SET LOCAL` session settings the policies read (DOMAIN-RULES §1.3). */
export const SESSION_SETTINGS = {
  brandIds: 'app.brand_ids',
  departmentIds: 'app.department_ids',
  allDepartments: 'app.all_departments',
  principalType: 'app.principal_type',
  principalId: 'app.principal_id',
} as const;

export interface TenantTable {
  readonly name: string;
  /**
   * Ticket-scoped tables carry a denormalised `department_id` and additionally
   * enforce department scope, so policies never need a join (DOMAIN-RULES §1.3).
   */
  readonly departmentScoped: boolean;
}

/**
 * Every table under row-level security. Adding a tenant table means adding it
 * here, regenerating the policy migration with `pnpm --filter @helpdock/db
 * gen:rls`, and extending the negative suite in `rls.integration.test.ts`, which
 * fails until the new table appears in it (DOMAIN-RULES §1.6).
 */
export const TENANT_TABLES: readonly TenantTable[] = [
  { name: 'user_brand_roles', departmentScoped: false },
  { name: 'settings', departmentScoped: false },
  { name: 'audit_log', departmentScoped: false },
  { name: 'outbox', departmentScoped: false },
];

/**
 * Tables that are deliberately not tenant-scoped, with the reason. A table is
 * on one of these two lists or it is a mistake.
 */
export const GLOBAL_TABLES: readonly { readonly name: string; readonly reason: string }[] = [
  { name: 'users', reason: 'sign-in happens before any brand is known' },
  { name: 'brands', reason: 'the tenant itself, managed by audited install-admin paths' },
  { name: 'job_receipts', reason: 'claimed by a worker before it opens a brand transaction' },
];

// A policy body is assembled as text, so anything interpolated into it has to be
// an identifier we recognise rather than a caller's string.
const IDENTIFIER = /^[a-z_][a-z0-9_]*$/;

const assertIdentifier = (value: string): string => {
  if (!IDENTIFIER.test(value)) {
    throw new TypeError(`${value} is not a valid unquoted SQL identifier`);
  }
  return value;
};

/** `nullif(…, '')` so that an unset or empty setting is null and the policy denies. */
const uuidArraySetting = (name: string): string =>
  `nullif(current_setting('${name}', true), '')::uuid[]`;

const booleanSetting = (name: string): string =>
  `coalesce(nullif(current_setting('${name}', true), '')::boolean, false)`;

/**
 * The predicate every policy on a tenant table uses. Without a tenant context
 * the setting is null, `= ANY(null)` is null, and the row is invisible: the
 * failure mode is "nothing", never "everything".
 */
export const tenantPredicate = ({ name, departmentScoped }: TenantTable): string => {
  assertIdentifier(name);
  const brand = `brand_id = ANY (${uuidArraySetting(SESSION_SETTINGS.brandIds)})`;
  if (!departmentScoped) {
    return brand;
  }

  const department = `${booleanSetting(SESSION_SETTINGS.allDepartments)} OR department_id = ANY (${uuidArraySetting(SESSION_SETTINGS.departmentIds)})`;
  return `${brand}\n    AND (${department})`;
};

/**
 * The statements that put one table under row-level security: enable it, force
 * it so the table owner is bound by it too (DOMAIN-RULES §1.5), and one policy
 * per command. Returned as separate statements because a migration file runs
 * them one at a time.
 */
export const tenantPolicies = (
  name: string,
  { departmentScoped = false }: { readonly departmentScoped?: boolean } = {},
): readonly string[] => {
  const table = assertIdentifier(name);
  const predicate = tenantPredicate({ name: table, departmentScoped });

  return [
    `ALTER TABLE "${table}" ENABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE "${table}" FORCE ROW LEVEL SECURITY;`,
    `CREATE POLICY "${table}_tenant_select" ON "${table}" FOR SELECT\n  USING (${predicate});`,
    `CREATE POLICY "${table}_tenant_insert" ON "${table}" FOR INSERT\n  WITH CHECK (${predicate});`,
    `CREATE POLICY "${table}_tenant_update" ON "${table}" FOR UPDATE\n  USING (${predicate})\n  WITH CHECK (${predicate});`,
    `CREATE POLICY "${table}_tenant_delete" ON "${table}" FOR DELETE\n  USING (${predicate});`,
  ];
};

/** Separator drizzle-kit writes between the statements of a migration file. */
const STATEMENT_BREAKPOINT = '--> statement-breakpoint';

const MIGRATION_HEADER = `-- Generated by \`pnpm --filter @helpdock/db gen:rls\` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- \`app.*\` settings the request transaction sets.`;

/** The whole policy migration, so the committed SQL and `TENANT_TABLES` cannot drift. */
export const renderTenantPolicyMigration = (
  tables: readonly TenantTable[] = TENANT_TABLES,
): string => {
  const statements = tables.flatMap((table) =>
    tenantPolicies(table.name, { departmentScoped: table.departmentScoped }),
  );

  return `${MIGRATION_HEADER}\n${statements.join(`\n${STATEMENT_BREAKPOINT}\n`)}\n`;
};
