/**
 * Copies the woff2 files Helpdock serves out of the `@fontsource/*` packages
 * into `packages/ui/fonts/` and regenerates `fonts/fonts.css`.
 *
 * The fonts are committed so a clone builds without a font download, and this
 * script is how they are reproduced. Run it from the package:
 *
 *     pnpm --filter @helpdock/ui sync:fonts
 *
 * DESIGN §3 fixes the families and the three weights. Adding a weight here
 * means changing DESIGN §3 first.
 */

import { copyFile, mkdir, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);
const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fontsDir = path.join(packageRoot, 'fonts');

interface FamilyPlan {
  /** The `@fontsource/*` package the files come from. */
  readonly source: string;
  /** Subsets to ship, by unicode-range. Anything else is dropped. */
  readonly subsets: readonly string[];
  readonly weights: readonly number[];
}

/** Total budget for `fonts/`, from the deliverable. */
export const FONT_BUDGET_BYTES = 1_500_000;

export const FAMILY_PLANS: readonly FamilyPlan[] = [
  {
    source: '@fontsource/ibm-plex-sans',
    subsets: ['latin', 'latin-ext'],
    weights: [400, 500, 600],
  },
  {
    source: '@fontsource/ibm-plex-sans-arabic',
    subsets: ['arabic', 'latin'],
    weights: [400, 500, 600],
  },
  {
    source: '@fontsource/ibm-plex-mono',
    subsets: ['latin', 'latin-ext'],
    weights: [400, 500],
  },
];

interface FontsourceMetadata {
  readonly family: string;
  readonly license: { readonly type: string; readonly url: string; readonly attribution: string };
  readonly version: string;
}

export interface FaceDescriptor {
  readonly family: string;
  readonly weight: number;
  readonly subset: string;
  readonly file: string;
  readonly unicodeRange: string;
}

/** The basename fontsource gives a file, e.g. `ibm-plex-sans-latin-400-normal`. */
const faceId = (source: string, subset: string, weight: number): string =>
  `${source.replace('@fontsource/', '')}-${subset}-${weight}-normal`;

function planFaces(plan: FamilyPlan, metadata: FontsourceMetadata): FaceDescriptor[] {
  const unicode = require(`${plan.source}/unicode.json`) as Record<string, string | undefined>;

  return plan.weights.flatMap((weight) =>
    plan.subsets.map((subset) => {
      const unicodeRange = unicode[subset];
      if (!unicodeRange) {
        throw new Error(`${plan.source} has no unicode range for subset ${subset}`);
      }

      const id = faceId(plan.source, subset, weight);

      return {
        family: metadata.family,
        weight,
        subset,
        file: `${id}.woff2`,
        unicodeRange,
      };
    }),
  );
}

const renderFace = (face: FaceDescriptor): string =>
  [
    `/* ${face.family} ${face.weight} · ${face.subset} */`,
    '@font-face {',
    `  font-family: '${face.family}';`,
    '  font-style: normal;',
    '  font-display: swap;',
    `  font-weight: ${face.weight};`,
    `  src: url('./${face.file}') format('woff2');`,
    `  unicode-range: ${face.unicodeRange};`,
    '}',
  ].join('\n');

function renderStylesheet(faces: readonly FaceDescriptor[], licenses: readonly string[]): string {
  return [
    '/*',
    ' * Generated by `pnpm --filter @helpdock/ui sync:fonts`. Do not edit by hand.',
    ' *',
    ...licenses.map((line) => ` * ${line}`),
    ' */',
    '',
    ...faces.map(renderFace),
    '',
  ].join('\n');
}

async function directorySizeBytes(directory: string): Promise<number> {
  const sizes = await Promise.all(
    (await readdir(directory)).map(async (entry) => (await stat(path.join(directory, entry))).size),
  );

  return sizes.reduce((total, size) => total + size, 0);
}

export async function syncFonts(): Promise<{ faces: FaceDescriptor[]; bytes: number }> {
  await rm(fontsDir, { recursive: true, force: true });
  await mkdir(fontsDir, { recursive: true });

  const faces: FaceDescriptor[] = [];
  const licenses: string[] = [];

  for (const plan of FAMILY_PLANS) {
    const metadataPath = require.resolve(`${plan.source}/metadata.json`);
    const metadata = require(metadataPath) as FontsourceMetadata;
    licenses.push(
      `${metadata.family} ${metadata.version} — ${metadata.license.type}, ${metadata.license.url}`,
    );

    const filesDir = path.join(path.dirname(metadataPath), 'files');
    for (const face of planFaces(plan, metadata)) {
      await copyFile(path.join(filesDir, face.file), path.join(fontsDir, face.file));
      faces.push(face);
    }
  }

  await writeFile(path.join(fontsDir, 'fonts.css'), renderStylesheet(faces, licenses), 'utf8');

  const bytes = await directorySizeBytes(fontsDir);
  if (bytes > FONT_BUDGET_BYTES) {
    throw new Error(
      `fonts/ is ${bytes} bytes, over the ${FONT_BUDGET_BYTES} byte budget. Drop a subset or a weight.`,
    );
  }

  return { faces, bytes };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { faces, bytes } = await syncFonts();
  process.stdout.write(
    `Wrote ${faces.length} faces (${(bytes / 1024).toFixed(0)} KiB) to packages/ui/fonts\n`,
  );
}
