import type { DbTransaction } from '@helpdock/db';
import type { EmailRepository } from './email.repository.js';
import type { EmailReceivedEvent } from './email-events.js';
import type { OutboundEmailService } from './outbound-email.service.js';
import { DEFAULT_HOURLY_CAP } from './outgoing-settings.js';

/**
 * M2-06: the acknowledgment and the out-of-hours reply, and the loop
 * protection around both (REQUIREMENTS §4.4).
 *
 * The decision, in order — each step is a reason not to send, and the first
 * one that applies is the outcome the log records:
 *
 * 1. Only an email that **opened** a ticket is answered; a customer's second
 *    message on the same request is not acknowledged again.
 * 2. Never to a machine: `Auto-Submitted`, `Precedence: bulk / list`,
 *    `noreply@`, `mailer-daemon@` (`isAutoGeneratedEmail`, computed by the
 *    inbound adapter from the headers it parsed).
 * 3. Out of hours and the out-of-hours reply on: that one, *instead of* the
 *    acknowledgment. Otherwise the acknowledgment, if on.
 * 4. At most `auto_reply_hourly_cap` auto-replies to one address per rolling
 *    hour, for a sender that loops without saying so. Mail past the cap still
 *    opens tickets; it just is not answered.
 * 5. At most one of each per ticket, by the unique index, so a redelivered
 *    event sends nothing new.
 */

/**
 * "Is this department open now?" — M3's business hours (M3-01), owned by the
 * SLA work. Until it is wired, every hour counts as open, which is what the
 * artboard promises with no hours set: the out-of-hours reply is never sent.
 */
export interface BusinessHoursProbe {
  isOpen(
    tx: DbTransaction,
    at: { readonly brandId: string; readonly departmentId: string; readonly at: Date },
  ): Promise<boolean>;
}

export const ALWAYS_OPEN: BusinessHoursProbe = {
  isOpen: () => Promise.resolve(true),
};

export type AutoReplyOutcome =
  | 'not-new-ticket'
  | 'auto-generated'
  | 'disabled'
  | 'capped'
  | 'not-queued'
  | 'acknowledgment'
  | 'out_of_hours';

const HOUR_MS = 3_600_000;

export class AutoReplyService {
  readonly #repository: EmailRepository;
  readonly #outbound: OutboundEmailService;
  readonly #hours: BusinessHoursProbe;
  readonly #now: () => Date;

  constructor(
    repository: EmailRepository,
    outbound: OutboundEmailService,
    hours: BusinessHoursProbe = ALWAYS_OPEN,
    now: () => Date = () => new Date(),
  ) {
    this.#repository = repository;
    this.#outbound = outbound;
    this.#hours = hours;
    this.#now = now;
  }

  async onInboundEmail(
    tx: DbTransaction,
    brandId: string,
    event: EmailReceivedEvent,
  ): Promise<AutoReplyOutcome> {
    if (!event.createdTicket) {
      return 'not-new-ticket';
    }
    if (event.autoGenerated) {
      return 'auto-generated';
    }

    const settings = await this.#repository.settings(tx, brandId);
    const acknowledgment = settings?.acknowledgmentEnabled ?? false;
    const outOfHours = settings?.outOfHoursEnabled ?? false;
    if (!acknowledgment && !outOfHours) {
      return 'disabled';
    }

    const addressing = await this.#repository.replyAddressing(tx, event.ticketId);
    if (addressing === undefined) {
      return 'disabled';
    }

    const now = this.#now();
    const open = outOfHours
      ? await this.#hours.isOpen(tx, { brandId, departmentId: addressing.departmentId, at: now })
      : true;
    const kind = !open && outOfHours ? 'out_of_hours' : acknowledgment ? 'acknowledgment' : null;
    if (kind === null) {
      return 'disabled';
    }

    const cap = settings?.autoReplyHourlyCap ?? DEFAULT_HOURLY_CAP;
    const recent = await this.#repository.autoRepliesTo(
      tx,
      event.from,
      new Date(now.getTime() - HOUR_MS),
    );
    if (recent >= cap) {
      return 'capped';
    }

    const delivery = await this.#outbound.queueAutoReply(tx, {
      brandId,
      ticketId: event.ticketId,
      kind,
      to: { address: event.from, name: event.fromName },
    });
    // Undefined when the brand has no sender at all, or this ticket already had
    // its auto-reply of this kind.
    return delivery === undefined ? 'not-queued' : kind;
  }
}
