import { describe, expect, it } from 'vitest';
import { FakeEmailRepository, installSmtp, recordingTx } from '../testing/email-doubles.js';
import { BRAND, MESSAGE, settingsRow, TICKET } from '../testing/email-fixtures.js';
import { AutoReplyService, type BusinessHoursProbe } from './auto-reply.service.js';
import type { EmailReceivedEvent } from './email-events.js';
import { OutboundEmailService } from './outbound-email.service.js';

const NOW = new Date('2026-09-27T22:00:00Z');

const event = (overrides: Partial<EmailReceivedEvent> = {}): EmailReceivedEvent => ({
  ticketId: TICKET,
  ticketMessageId: MESSAGE,
  createdTicket: true,
  from: 'mona@example.com',
  fromName: 'Mona Khalil',
  autoGenerated: false,
  ...overrides,
});

const setup = ({
  acknowledgment = true,
  outOfHours = false,
  open = true,
}: {
  acknowledgment?: boolean;
  outOfHours?: boolean;
  open?: boolean;
} = {}) => {
  const repository = new FakeEmailRepository();
  repository.settingsRow = settingsRow({
    acknowledgmentEnabled: acknowledgment,
    outOfHoursEnabled: outOfHours,
  });
  const asked: unknown[] = [];
  const hours: BusinessHoursProbe = {
    isOpen: async (_tx, at) => {
      asked.push(at);
      return open;
    },
  };
  const service = new AutoReplyService(
    repository.asRepository,
    new OutboundEmailService(repository.asRepository, installSmtp()),
    hours,
    () => NOW,
  );
  return { repository, service, asked, ...recordingTx() };
};

describe('AutoReplyService', () => {
  it('acknowledges an email that opened a ticket', async () => {
    const { service, tx, repository } = setup();

    expect(await service.onInboundEmail(tx, BRAND, event())).toBe('acknowledgment');
    expect(repository.deliveries[0]).toMatchObject({
      kind: 'acknowledgment',
      toAddress: 'mona@example.com',
    });
  });

  it('does not acknowledge a later message on the same request', async () => {
    const { service, tx } = setup();

    expect(await service.onInboundEmail(tx, BRAND, event({ createdTicket: false }))).toBe(
      'not-new-ticket',
    );
  });

  it('never answers a machine', async () => {
    const { service, tx, repository } = setup();

    expect(await service.onInboundEmail(tx, BRAND, event({ autoGenerated: true }))).toBe(
      'auto-generated',
    );
    expect(repository.deliveries).toEqual([]);
  });

  it('sends nothing while both replies are off', async () => {
    const { service, tx } = setup({ acknowledgment: false });

    expect(await service.onInboundEmail(tx, BRAND, event())).toBe('disabled');
  });

  it('sends the out-of-hours reply instead of the acknowledgment when closed', async () => {
    const { service, tx, repository, asked } = setup({ outOfHours: true, open: false });

    expect(await service.onInboundEmail(tx, BRAND, event())).toBe('out_of_hours');
    expect(repository.deliveries.map((row) => row.kind)).toEqual(['out_of_hours']);
    expect(asked).toEqual([{ brandId: BRAND, departmentId: expect.any(String), at: NOW }]);
  });

  it('acknowledges as usual when the out-of-hours reply is on but the desk is open', async () => {
    const { service, tx } = setup({ outOfHours: true, open: true });

    expect(await service.onInboundEmail(tx, BRAND, event())).toBe('acknowledgment');
  });

  it('does nothing out of hours with only the out-of-hours reply off and no acknowledgment', async () => {
    const { service, tx, asked } = setup({ acknowledgment: false, outOfHours: false });

    expect(await service.onInboundEmail(tx, BRAND, event())).toBe('disabled');
    expect(asked).toEqual([]);
  });

  it('stops at the per-sender cap, whatever else would send', async () => {
    const { service, tx, repository } = setup();
    repository.recentAutoReplies = 3;

    expect(await service.onInboundEmail(tx, BRAND, event())).toBe('capped');
    expect(repository.deliveries).toEqual([]);
  });

  it('queues one acknowledgment per ticket, however often the event arrives', async () => {
    const { service, tx, outbox } = setup();

    await service.onInboundEmail(tx, BRAND, event());
    expect(await service.onInboundEmail(tx, BRAND, event())).toBe('not-queued');
    expect(outbox).toHaveLength(1);
  });

  it('treats a ticket it cannot see as nothing to answer', async () => {
    const { service, tx, repository } = setup();
    repository.addressingRow = undefined;

    expect(await service.onInboundEmail(tx, BRAND, event())).toBe('disabled');
  });

  it('counts every hour as open by default', async () => {
    const repository = new FakeEmailRepository();
    repository.settingsRow = settingsRow({ acknowledgmentEnabled: true, outOfHoursEnabled: true });
    const service = new AutoReplyService(
      repository.asRepository,
      new OutboundEmailService(repository.asRepository, installSmtp()),
    );

    expect(await service.onInboundEmail(recordingTx().tx, BRAND, event())).toBe('acknowledgment');
  });
});
