import type { DbTransaction } from '@helpdock/db';
import {
  enqueueOutbox,
  type OutboxEventContext,
  type OutboxEventHandler,
  registerEventHandler,
} from '@helpdock/jobs';
import { z } from 'zod';
import type { AutoReplyService } from './auto-reply.service.js';

/**
 * M2-05 and M2-06's two outbox events.
 *
 * ```
 * reply / inbound mail → email_deliveries + outbox(email.send)   (one transaction)
 * relay                → BullMQ outbox.event                      (after commit)
 * worker               → this handler → BullMQ email.send          (jobId = outbox id)
 * email.send consumer  → SMTP, then the row is `sent`             (with its receipt)
 * ```
 *
 * `email.send` goes through the outbox rather than straight onto the
 * `outbound` queue for the reason every side effect does (DOMAIN-RULES §6): a
 * reply that rolls back must not send. Its handler adds the job with the outbox
 * row's id as the job id, so a redelivered event adds nothing; a retry from
 * Failed sends writes a new outbox row, which is a new job for the same
 * delivery.
 *
 * `email.received` is the seam with the inbound adapters (M2-02, M2-03): they
 * write it in the transaction that files an inbound email, and M2-06's
 * auto-responder decides here, in the worker, whether it deserves a reply.
 */

export const EMAIL_EVENTS = {
  send: 'email.send',
  received: 'email.received',
} as const;

export const emailSendEventSchema = z.object({ deliveryId: z.uuid() });
export type EmailSendEvent = z.infer<typeof emailSendEventSchema>;

export const emailReceivedEventSchema = z.object({
  ticketId: z.uuid(),
  /** The inbound message, for the log. */
  ticketMessageId: z.uuid(),
  /** True when this email opened the ticket. Only a new ticket is acknowledged. */
  createdTicket: z.boolean(),
  /** The sender's normalised address: who the auto-reply goes to. */
  from: z.email(),
  fromName: z.string().max(200).optional(),
  /**
   * `isAutoGeneratedEmail` from `@helpdock/channels`, computed by the adapter
   * from the headers it parsed: `Auto-Submitted`, `Precedence`, `noreply@`.
   */
  autoGenerated: z.boolean(),
});
export type EmailReceivedEvent = z.infer<typeof emailReceivedEventSchema>;

export const enqueueEmailSend = (
  tx: DbTransaction,
  brandId: string,
  deliveryId: string,
): Promise<string> =>
  enqueueOutbox(tx, {
    brandId,
    event: EMAIL_EVENTS.send,
    payload: emailSendEventSchema.parse({ deliveryId }),
  });

/** For the inbound adapters: call in the transaction that filed the email. */
export const enqueueEmailReceived = (
  tx: DbTransaction,
  brandId: string,
  event: EmailReceivedEvent,
): Promise<string> =>
  enqueueOutbox(tx, {
    brandId,
    event: EMAIL_EVENTS.received,
    payload: emailReceivedEventSchema.parse(event),
  });

/** The producer half of `email.send`; the worker hands it a BullMQ queue. */
export interface EmailSendQueue {
  add(input: { jobId: string; payload: { brandId: string; deliveryId: string } }): Promise<void>;
}

/** BullMQ refuses a custom job id with a colon; the outbox id has none. */
export const emailSendJobId = (outboxId: string): string => `email.send.${outboxId}`;

export const createEmailSendEventHandler =
  (queue: EmailSendQueue): OutboxEventHandler =>
  async ({ brandId, outboxId, payload }: OutboxEventContext): Promise<void> => {
    const { deliveryId } = emailSendEventSchema.parse(payload);
    await queue.add({ jobId: emailSendJobId(outboxId), payload: { brandId, deliveryId } });
  };

export const createEmailReceivedEventHandler =
  (autoReplies: AutoReplyService): OutboxEventHandler =>
  async ({ brandId, payload, tx, log }: OutboxEventContext): Promise<void> => {
    const event = emailReceivedEventSchema.parse(payload);
    const outcome = await autoReplies.onInboundEmail(tx, brandId, event);
    log.info(
      { brandId, ticketId: event.ticketId, outcome },
      'auto-reply decided for an inbound email',
    );
  };

/** Called by the worker's start-up, before the consumer exists (`worker/start-worker.ts`). */
export const registerEmailEventHandlers = ({
  queue,
  autoReplies,
}: {
  readonly queue: EmailSendQueue;
  readonly autoReplies: AutoReplyService;
}): void => {
  registerEventHandler(EMAIL_EVENTS.send, createEmailSendEventHandler(queue));
  registerEventHandler(EMAIL_EVENTS.received, createEmailReceivedEventHandler(autoReplies));
};
