import { createOutboxDispatcher, silentLogger } from '@helpdock/jobs';
import { describe, expect, it } from 'vitest';
import { recordingTx } from '../testing/email-doubles.js';
import { BRAND, DELIVERY, MESSAGE, TICKET } from '../testing/email-fixtures.js';
import type { AutoReplyService } from './auto-reply.service.js';
import {
  createEmailReceivedEventHandler,
  createEmailSendEventHandler,
  EMAIL_EVENTS,
  emailSendJobId,
  enqueueEmailReceived,
  enqueueEmailSend,
} from './email-events.js';

const OUTBOX_ID = '0190a8a5-7c1e-7000-8000-0000000000aa';

describe('email.send', () => {
  it('adds one job per outbox row, keyed by the row', async () => {
    const added: unknown[] = [];
    const handler = createEmailSendEventHandler({ add: async (input) => void added.push(input) });

    await handler({
      outboxId: OUTBOX_ID,
      brandId: BRAND,
      event: EMAIL_EVENTS.send,
      payload: { deliveryId: DELIVERY },
      tx: recordingTx().tx,
      log: silentLogger,
    });

    expect(added).toEqual([
      { jobId: `email.send.${OUTBOX_ID}`, payload: { brandId: BRAND, deliveryId: DELIVERY } },
    ]);
    expect(emailSendJobId(OUTBOX_ID)).not.toContain(':');
  });

  it('writes the outbox row through the caller transaction', async () => {
    const { tx, outbox } = recordingTx();

    await enqueueEmailSend(tx, BRAND, DELIVERY);

    expect(outbox).toEqual([{ event: 'email.send', payload: { deliveryId: DELIVERY } }]);
  });
});

describe('email.received', () => {
  const event = {
    ticketId: TICKET,
    ticketMessageId: MESSAGE,
    createdTicket: true,
    from: 'mona@example.com',
    autoGenerated: false,
  };

  it('hands the inbound email to the auto-responder', async () => {
    const seen: unknown[] = [];
    const autoReplies = {
      onInboundEmail: async (_tx: unknown, brandId: string, received: unknown) => {
        seen.push({ brandId, received });
        return 'acknowledgment' as const;
      },
    } as unknown as AutoReplyService;
    const dispatcher = createOutboxDispatcher();
    dispatcher.register(EMAIL_EVENTS.received, createEmailReceivedEventHandler(autoReplies));

    await dispatcher.dispatch({
      outboxId: OUTBOX_ID,
      brandId: BRAND,
      event: EMAIL_EVENTS.received,
      payload: event,
      tx: recordingTx().tx,
      log: silentLogger,
    });

    expect(seen).toEqual([{ brandId: BRAND, received: event }]);
  });

  it('refuses an event that does not say whether a machine sent it', async () => {
    const { tx } = recordingTx();
    const { autoGenerated: _, ...incomplete } = event;

    expect(() => enqueueEmailReceived(tx, BRAND, incomplete as typeof event)).toThrow();
  });
});
