CREATE TYPE "public"."brand_domain_kind" AS ENUM('helpcenter', 'widget_origin');--> statement-breakpoint
CREATE TABLE "brand_domains" (
	"id" uuid PRIMARY KEY NOT NULL,
	"brand_id" uuid NOT NULL,
	"domain" text NOT NULL,
	"kind" "brand_domain_kind" NOT NULL,
	"verified_at" timestamp with time zone,
	"txt_token" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "brand_domains_domain_unique" UNIQUE("domain")
);
--> statement-breakpoint
ALTER TABLE "brand_domains" ADD CONSTRAINT "brand_domains_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "brand_domains" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "brand_domains" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "brand_domains_tenant_select" ON "brand_domains" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "brand_domains_tenant_insert" ON "brand_domains" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "brand_domains_tenant_update" ON "brand_domains" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "brand_domains_tenant_delete" ON "brand_domains" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
