CREATE TYPE "public"."attachment_kind" AS ENUM('image', 'video', 'audio', 'file');--> statement-breakpoint
CREATE TYPE "public"."attachment_reject_reason" AS ENUM('mime_mismatch', 'mime_not_allowed', 'kind_disabled', 'too_large', 'object_missing', 'unreadable', 'timeout', 'scan_error', 'infected', 'processing_failed');--> statement-breakpoint
CREATE TYPE "public"."attachment_scan_status" AS ENUM('skipped', 'clean', 'infected', 'error');--> statement-breakpoint
CREATE TYPE "public"."attachment_status" AS ENUM('pending', 'processing', 'ready', 'rejected', 'infected');--> statement-breakpoint
CREATE TYPE "public"."attachment_uploader_type" AS ENUM('staff', 'contact', 'system');--> statement-breakpoint
CREATE TABLE "attachments" (
	"id" uuid PRIMARY KEY NOT NULL,
	"brand_id" uuid NOT NULL,
	"ticket_id" uuid NOT NULL,
	"department_id" uuid NOT NULL,
	"message_id" uuid,
	"uploader_type" "attachment_uploader_type" NOT NULL,
	"uploader_id" text NOT NULL,
	"s3_key" text NOT NULL,
	"original_name" text NOT NULL,
	"mime" text NOT NULL,
	"size" bigint NOT NULL,
	"kind" "attachment_kind" NOT NULL,
	"status" "attachment_status" DEFAULT 'pending' NOT NULL,
	"reject_reason" "attachment_reject_reason",
	"variants" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"scan_status" "attachment_scan_status" DEFAULT 'skipped' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"processed_at" timestamp with time zone,
	CONSTRAINT "attachments_s3_key_unique" UNIQUE("s3_key")
);
--> statement-breakpoint
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_department_id_departments_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_message_id_ticket_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."ticket_messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "attachments_message_idx" ON "attachments" USING btree ("message_id");--> statement-breakpoint
CREATE INDEX "attachments_ticket_idx" ON "attachments" USING btree ("ticket_id");--> statement-breakpoint
CREATE INDEX "attachments_brand_department_idx" ON "attachments" USING btree ("brand_id","department_id");
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "attachments" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "attachments" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "attachments_tenant_select" ON "attachments" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
CREATE POLICY "attachments_tenant_insert" ON "attachments" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
CREATE POLICY "attachments_tenant_update" ON "attachments" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
CREATE POLICY "attachments_tenant_delete" ON "attachments" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
-- What the Drizzle schema cannot express: an attachment is a child of a ticket,
-- so it carries the same denormalised `department_id` the thread does and is
-- kept true by the same trigger function `0008_ticket_department_sync.sql`
-- installed (DOMAIN-RULES §1.3 layer 3).
--
-- Whatever a caller passes is overwritten with the parent ticket's department,
-- and a ticket the caller cannot see yields no department at all, so the insert
-- is refused with `insufficient_privilege` rather than stored under a
-- department its ticket is not in. That is "may this principal attach to this
-- ticket" answered once, in the database.
CREATE TRIGGER attachments_department
BEFORE INSERT ON public.attachments
FOR EACH ROW
EXECUTE FUNCTION public.helpdock_ticket_child_department();--> statement-breakpoint

-- A ticket that moves department already takes its thread and its activity log
-- with it. Its attachments have to move too: an attachment left behind would
-- stay readable by the department the ticket has left and be invisible to the
-- one it arrived in, so the presigned-download endpoint would answer 404 for
-- the agent now working the ticket.
--
-- `CREATE OR REPLACE` rather than a second trigger, so there is still one
-- function that knows what a ticket's children are.
CREATE OR REPLACE FUNCTION public.helpdock_ticket_department_moved()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  UPDATE public.ticket_messages
  SET department_id = NEW.department_id
  WHERE ticket_id = NEW.id;

  UPDATE public.ticket_activity
  SET department_id = NEW.department_id
  WHERE ticket_id = NEW.id;

  UPDATE public.attachments
  SET department_id = NEW.department_id
  WHERE ticket_id = NEW.id;

  RETURN NULL;
END;
$$;
