CREATE TYPE "public"."assignment_mode" AS ENUM('manual', 'round_robin', 'skill_based');--> statement-breakpoint
CREATE TYPE "public"."on_unassign" AS ENUM('round_robin', 'leave_unassigned');--> statement-breakpoint
CREATE TABLE "assignment_agents" (
	"brand_id" uuid NOT NULL,
	"department_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"in_rotation" boolean NOT NULL,
	"last_assigned_at" timestamp (3) with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "assignment_agents_pkey" PRIMARY KEY("department_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "assignment_skills" (
	"brand_id" uuid NOT NULL,
	"department_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"tag_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "assignment_skills_pkey" PRIMARY KEY("department_id","user_id","tag_id")
);
--> statement-breakpoint
ALTER TABLE "departments" ADD COLUMN "assignment_mode" "assignment_mode" DEFAULT 'manual' NOT NULL;--> statement-breakpoint
ALTER TABLE "departments" ADD COLUMN "load_cap" integer;--> statement-breakpoint
ALTER TABLE "departments" ADD COLUMN "auto_unassign_offline" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "departments" ADD COLUMN "auto_unassign_after_minutes" integer DEFAULT 15 NOT NULL;--> statement-breakpoint
ALTER TABLE "departments" ADD COLUMN "on_unassign" "on_unassign" DEFAULT 'leave_unassigned' NOT NULL;--> statement-breakpoint
ALTER TABLE "assignment_agents" ADD CONSTRAINT "assignment_agents_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignment_agents" ADD CONSTRAINT "assignment_agents_department_id_departments_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignment_agents" ADD CONSTRAINT "assignment_agents_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignment_skills" ADD CONSTRAINT "assignment_skills_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignment_skills" ADD CONSTRAINT "assignment_skills_department_id_departments_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignment_skills" ADD CONSTRAINT "assignment_skills_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignment_skills" ADD CONSTRAINT "assignment_skills_tag_id_tags_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "assignment_agents_brand_user_idx" ON "assignment_agents" USING btree ("brand_id","user_id");--> statement-breakpoint
CREATE INDEX "assignment_skills_brand_tag_idx" ON "assignment_skills" USING btree ("brand_id","tag_id");--> statement-breakpoint
ALTER TABLE "departments" ADD CONSTRAINT "departments_load_cap_positive" CHECK ("departments"."load_cap" IS NULL OR "departments"."load_cap" > 0);--> statement-breakpoint
ALTER TABLE "departments" ADD CONSTRAINT "departments_auto_unassign_minutes_range" CHECK ("departments"."auto_unassign_after_minutes" BETWEEN 1 AND 1440);
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "assignment_agents" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "assignment_agents" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "assignment_agents_tenant_select" ON "assignment_agents" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "assignment_agents_tenant_insert" ON "assignment_agents" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "assignment_agents_tenant_update" ON "assignment_agents" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "assignment_agents_tenant_delete" ON "assignment_agents" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
ALTER TABLE "assignment_skills" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "assignment_skills" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "assignment_skills_tenant_select" ON "assignment_skills" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "assignment_skills_tenant_insert" ON "assignment_skills" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "assignment_skills_tenant_update" ON "assignment_skills" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "assignment_skills_tenant_delete" ON "assignment_skills" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
