CREATE TYPE "public"."blocked_sender_kind" AS ENUM('email', 'domain', 'phone', 'telegram');--> statement-breakpoint
CREATE TABLE "blocked_senders" (
	"id" uuid PRIMARY KEY NOT NULL,
	"brand_id" uuid NOT NULL,
	"kind" "blocked_sender_kind" NOT NULL,
	"value" text NOT NULL,
	"created_by" uuid,
	"source_ticket_id" uuid,
	"dropped_count" integer DEFAULT 0 NOT NULL,
	"last_dropped_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "blocked_senders_brand_kind_value_key" UNIQUE("brand_id","kind","value")
);
--> statement-breakpoint
ALTER TABLE "ticket_statuses" ADD COLUMN "is_spam" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "blocked_senders" ADD CONSTRAINT "blocked_senders_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blocked_senders" ADD CONSTRAINT "blocked_senders_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
-- Brands seeded before M1-11 already have a Spam row; mark it. It is found by
-- what the seed wrote, English or Arabic name, because a flag is the only way
-- to find it from here on and nothing else tells it apart from Merged. The
-- same statement repairs `excluded_from_reports`, which rows seeded before
-- migration 0012 do not carry.
UPDATE "ticket_statuses" SET "is_spam" = true, "excluded_from_reports" = true
  WHERE "is_system" AND "system_state" = 'closed' AND ("name" = 'Spam' OR "name_ar" = 'بريد مزعج');--> statement-breakpoint
CREATE UNIQUE INDEX "ticket_statuses_brand_spam_key" ON "ticket_statuses" USING btree ("brand_id") WHERE "ticket_statuses"."is_spam";
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "blocked_senders" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "blocked_senders" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "blocked_senders_tenant_select" ON "blocked_senders" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "blocked_senders_tenant_insert" ON "blocked_senders" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "blocked_senders_tenant_update" ON "blocked_senders" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "blocked_senders_tenant_delete" ON "blocked_senders" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
