CREATE TYPE "public"."blocked_sender_kind" AS ENUM('email', 'domain', 'phone', 'telegram');--> statement-breakpoint
CREATE TABLE "blocked_senders" (
	"id" uuid PRIMARY KEY NOT NULL,
	"brand_id" uuid NOT NULL,
	"kind" "blocked_sender_kind" NOT NULL,
	"value" text NOT NULL,
	"created_by" uuid,
	"source_ticket_id" uuid,
	"dropped_count" integer DEFAULT 0 NOT NULL,
	"last_dropped_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "blocked_senders_brand_kind_value_key" UNIQUE("brand_id","kind","value")
);
--> statement-breakpoint
ALTER TABLE "blocked_senders" ADD CONSTRAINT "blocked_senders_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blocked_senders" ADD CONSTRAINT "blocked_senders_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
-- "Which row is Spam?" has one answer: `system_key = 'spam'` (M1-09, migration
-- 0016, which also gives existing brands their keys). `is_spam` is derived
-- from it, so the flag everything reads can never disagree with the key, and
-- the key's partial unique index already allows one Spam per brand.
--
-- Brands seeded before M1-11 whose Spam row the name match in 0016 missed —
-- renamed in English but still carrying the seeded Arabic name — get their key
-- here, and every Spam row gets `excluded_from_reports`, which rows seeded
-- before migration 0012 do not carry.
--
-- The table is under FORCE ROW LEVEL SECURITY, which binds the owner too and
-- would make these UPDATEs see no rows without a tenant context. The force is
-- lifted for them, inside the migration's transaction, and put back before
-- anything else can run.
ALTER TABLE "ticket_statuses" NO FORCE ROW LEVEL SECURITY;--> statement-breakpoint
UPDATE "ticket_statuses" SET "system_key" = 'spam'
  WHERE "is_system" AND "system_key" IS NULL AND "system_state" = 'closed' AND "name_ar" = 'بريد مزعج'
    AND NOT EXISTS (
      SELECT 1 FROM "ticket_statuses" AS "other"
      WHERE "other"."brand_id" = "ticket_statuses"."brand_id" AND "other"."system_key" = 'spam'
    );--> statement-breakpoint
UPDATE "ticket_statuses" SET "excluded_from_reports" = true WHERE "system_key" = 'spam';--> statement-breakpoint
ALTER TABLE "ticket_statuses" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ticket_statuses" ADD COLUMN "is_spam" boolean GENERATED ALWAYS AS (coalesce(system_key = 'spam', false)) STORED NOT NULL;
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "blocked_senders" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "blocked_senders" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "blocked_senders_tenant_select" ON "blocked_senders" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "blocked_senders_tenant_insert" ON "blocked_senders" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "blocked_senders_tenant_update" ON "blocked_senders" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "blocked_senders_tenant_delete" ON "blocked_senders" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
