CREATE TYPE "public"."contact_duplicate_reason" AS ENUM('email', 'phone', 'telegram', 'visitor', 'external', 'similar_name');--> statement-breakpoint
CREATE TYPE "public"."ticket_participant_source" AS ENUM('agent', 'email', 'merge');--> statement-breakpoint
CREATE TABLE "contact_merges" (
	"id" uuid PRIMARY KEY NOT NULL,
	"brand_id" uuid NOT NULL,
	"survivor_id" uuid NOT NULL,
	"merged_id" uuid NOT NULL,
	"suggestion_id" uuid,
	"actor_id" uuid,
	"moved_identity_ids" uuid[] DEFAULT '{}'::uuid[] NOT NULL,
	"moved_ticket_ids" uuid[] DEFAULT '{}'::uuid[] NOT NULL,
	"moved_note_ids" uuid[] DEFAULT '{}'::uuid[] NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"undo_until" timestamp with time zone NOT NULL,
	"undone_at" timestamp with time zone,
	"undone_by" uuid
);
--> statement-breakpoint
CREATE TABLE "ticket_participants" (
	"id" uuid PRIMARY KEY NOT NULL,
	"brand_id" uuid NOT NULL,
	"department_id" uuid NOT NULL,
	"ticket_id" uuid NOT NULL,
	"contact_id" uuid NOT NULL,
	"address" text,
	"source" "ticket_participant_source" NOT NULL,
	"added_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ticket_participants_ticket_contact_key" UNIQUE("ticket_id","contact_id")
);
--> statement-breakpoint
ALTER TABLE "contact_duplicate_suggestions" ALTER COLUMN "reason" SET DATA TYPE "public"."contact_duplicate_reason" USING "reason"::text::"public"."contact_duplicate_reason";--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "merged_into_id" uuid;--> statement-breakpoint
ALTER TABLE "contacts" ADD COLUMN "merged_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "contact_merges" ADD CONSTRAINT "contact_merges_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contact_merges" ADD CONSTRAINT "contact_merges_survivor_id_contacts_id_fk" FOREIGN KEY ("survivor_id") REFERENCES "public"."contacts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contact_merges" ADD CONSTRAINT "contact_merges_merged_id_contacts_id_fk" FOREIGN KEY ("merged_id") REFERENCES "public"."contacts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contact_merges" ADD CONSTRAINT "contact_merges_suggestion_id_contact_duplicate_suggestions_id_fk" FOREIGN KEY ("suggestion_id") REFERENCES "public"."contact_duplicate_suggestions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contact_merges" ADD CONSTRAINT "contact_merges_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contact_merges" ADD CONSTRAINT "contact_merges_undone_by_users_id_fk" FOREIGN KEY ("undone_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_participants" ADD CONSTRAINT "ticket_participants_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_participants" ADD CONSTRAINT "ticket_participants_department_id_departments_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_participants" ADD CONSTRAINT "ticket_participants_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_participants" ADD CONSTRAINT "ticket_participants_contact_id_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."contacts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_participants" ADD CONSTRAINT "ticket_participants_added_by_users_id_fk" FOREIGN KEY ("added_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "contact_merges_brand_survivor_idx" ON "contact_merges" USING btree ("brand_id","survivor_id");--> statement-breakpoint
CREATE INDEX "contact_merges_brand_merged_idx" ON "contact_merges" USING btree ("brand_id","merged_id");--> statement-breakpoint
CREATE INDEX "ticket_participants_brand_department_idx" ON "ticket_participants" USING btree ("brand_id","department_id");--> statement-breakpoint
CREATE INDEX "ticket_participants_brand_contact_idx" ON "ticket_participants" USING btree ("brand_id","contact_id");--> statement-breakpoint
ALTER TABLE "contacts" ADD CONSTRAINT "contacts_merged_into_id_contacts_id_fk" FOREIGN KEY ("merged_into_id") REFERENCES "public"."contacts"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "contact_merges" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "contact_merges" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "contact_merges_tenant_select" ON "contact_merges" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "contact_merges_tenant_insert" ON "contact_merges" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "contact_merges_tenant_update" ON "contact_merges" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "contact_merges_tenant_delete" ON "contact_merges" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
ALTER TABLE "ticket_participants" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ticket_participants" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "ticket_participants_tenant_select" ON "ticket_participants" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
CREATE POLICY "ticket_participants_tenant_insert" ON "ticket_participants" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
CREATE POLICY "ticket_participants_tenant_update" ON "ticket_participants" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
CREATE POLICY "ticket_participants_tenant_delete" ON "ticket_participants" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
-- `ticket_participants` is another child of a ticket and another department-
-- scoped table, so it joins the triggers `0008` wrote exactly as `ticket_tags`
-- did in `0014`. On the way in the trigger copies the parent's department and
-- refuses a ticket the transaction cannot see, which is what stops an agent
-- adding a CC to a ticket in a department they are not in.
CREATE TRIGGER ticket_participants_department
BEFORE INSERT ON public.ticket_participants
FOR EACH ROW
EXECUTE FUNCTION public.helpdock_ticket_child_department();--> statement-breakpoint

-- And on a move, the ticket takes its CCs with it. Replaced rather than joined
-- by a second trigger, so "what moves with a ticket" stays one list.
CREATE OR REPLACE FUNCTION public.helpdock_ticket_department_moved()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  UPDATE public.ticket_messages
  SET department_id = NEW.department_id
  WHERE ticket_id = NEW.id;

  UPDATE public.ticket_activity
  SET department_id = NEW.department_id
  WHERE ticket_id = NEW.id;

  UPDATE public.attachments
  SET department_id = NEW.department_id
  WHERE ticket_id = NEW.id;

  UPDATE public.ticket_tags
  SET department_id = NEW.department_id
  WHERE ticket_id = NEW.id;

  UPDATE public.ticket_participants
  SET department_id = NEW.department_id
  WHERE ticket_id = NEW.id;

  -- M1-12's children (migration 0018 added them to this function first; this
  -- migration runs after it, so the replacement has to carry them too).
  UPDATE public.ticket_time_entries
  SET department_id = NEW.department_id
  WHERE ticket_id = NEW.id;

  UPDATE public.csat_responses
  SET department_id = NEW.department_id
  WHERE ticket_id = NEW.id;

  RETURN NULL;
END;
$$;--> statement-breakpoint

-- A contact merge moves *all* of a contact's tickets to the survivor, and an
-- undo moves exactly those back (DOMAIN-RULES §4.4). "All" includes tickets in
-- departments the merging agent cannot see: a contact is brand-scoped, and a
-- merge that left the hidden half of somebody's history on a contact nobody
-- can find any more would split the person in two (§1.2).
--
-- The same shape as `helpdock_contact_ticket_count` in `0008`, and for the
-- same reasons: the function-level SET turns `app.all_departments` on for the
-- one call and restores it on return, `app.brand_ids` is untouched so the
-- brand policy still applies, and it runs with the caller's rights because
-- FORCEd row-level security binds an owner too. It changes one column,
-- `contact_id`, and returns ids the api stores on the merge record and never
-- sends to a client.
--
-- `p_ticket_ids` null means "every ticket of p_from"; an array narrows the
-- move to those ids, which is what an undo passes.
CREATE FUNCTION public.helpdock_contact_reassign_tickets(
  p_brand_id uuid,
  p_from uuid,
  p_to uuid,
  p_ticket_ids uuid[] DEFAULT NULL
)
RETURNS uuid[]
LANGUAGE sql
VOLATILE
SET search_path = ''
SET app.all_departments = 'true'
AS $$
  WITH moved AS (
    UPDATE public.tickets
    SET contact_id = p_to
    WHERE brand_id = p_brand_id
      AND contact_id = p_from
      AND (p_ticket_ids IS NULL OR id = ANY (p_ticket_ids))
    RETURNING id
  )
  SELECT coalesce(pg_catalog.array_agg(id), '{}'::uuid[]) FROM moved;
$$;
