CREATE TABLE "retention_settings" (
	"brand_id" uuid PRIMARY KEY NOT NULL,
	"closed_ticket_days" integer,
	"spam_ticket_days" integer DEFAULT 30 NOT NULL,
	"ai_call_days" integer DEFAULT 90 NOT NULL,
	"search_log_days" integer DEFAULT 180 NOT NULL,
	"audit_log_days" integer DEFAULT 730 NOT NULL,
	"visitor_session_days" integer DEFAULT 30 NOT NULL,
	"updated_by" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_run_at" timestamp with time zone,
	"last_run_counts" jsonb DEFAULT '{}'::jsonb NOT NULL,
	CONSTRAINT "retention_settings_closed_ticket_days_check" CHECK ("retention_settings"."closed_ticket_days" IS NULL OR "retention_settings"."closed_ticket_days" >= 1),
	CONSTRAINT "retention_settings_spam_ticket_days_check" CHECK ("retention_settings"."spam_ticket_days" >= 1),
	CONSTRAINT "retention_settings_ai_call_days_check" CHECK ("retention_settings"."ai_call_days" >= 1),
	CONSTRAINT "retention_settings_search_log_days_check" CHECK ("retention_settings"."search_log_days" >= 1),
	CONSTRAINT "retention_settings_audit_log_days_check" CHECK ("retention_settings"."audit_log_days" >= 90),
	CONSTRAINT "retention_settings_visitor_session_days_check" CHECK ("retention_settings"."visitor_session_days" >= 1)
);
--> statement-breakpoint
ALTER TABLE "ticket_statuses" ADD COLUMN "is_spam" boolean DEFAULT false NOT NULL;--> statement-breakpoint
-- Existing brands' seeded Spam row gets the flag. It is found the one way that
-- is still possible before the flag exists: the system row seeded as "Spam".
-- A brand that already renamed it keeps an unflagged row, and its spam is then
-- purged with the closed tickets instead — later, never sooner.
--
-- The table is under FORCE ROW LEVEL SECURITY, which binds the owner too and
-- would make this UPDATE see no rows without a tenant context. The force is
-- lifted for this one statement, inside the migration's transaction, and put
-- back before anything else can run.
ALTER TABLE "ticket_statuses" NO FORCE ROW LEVEL SECURITY;--> statement-breakpoint
UPDATE "ticket_statuses" SET "is_spam" = true
  WHERE "is_system" AND "system_state" = 'closed' AND "name" = 'Spam';--> statement-breakpoint
ALTER TABLE "ticket_statuses" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "retention_settings" ADD CONSTRAINT "retention_settings_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "tickets_brand_closed_at_idx" ON "tickets" USING btree ("brand_id","closed_at") WHERE "tickets"."closed_at" is not null;
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "retention_settings" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "retention_settings" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "retention_settings_tenant_select" ON "retention_settings" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "retention_settings_tenant_insert" ON "retention_settings" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "retention_settings_tenant_update" ON "retention_settings" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "retention_settings_tenant_delete" ON "retention_settings" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
