-- M1-05: saved views over the ticket list. Brand-scoped like every tenant
-- table, plus one restrictive policy (`views_owner_only`, from
-- OWNER_SCOPED_TABLES in src/rls.ts) that keeps a personal view its owner's
-- alone. The built-in defaults are rows too, written by `seedBrandViews` when a
-- brand or a department is created, not here: the owner running this migration
-- is bound by the forced policies and has no brand to write under.
CREATE TYPE "public"."ticket_view_built_in" AS ENUM('my_open', 'unassigned', 'overdue', 'department_open', 'escalated');--> statement-breakpoint
CREATE TABLE "views" (
	"id" uuid PRIMARY KEY NOT NULL,
	"brand_id" uuid NOT NULL,
	"owner_id" uuid,
	"name" varchar(160) NOT NULL,
	"name_ar" varchar(160),
	"filters" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"visible_department_ids" uuid[],
	"built_in" "ticket_view_built_in",
	"department_id" uuid,
	"hidden" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "views" ADD CONSTRAINT "views_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "views" ADD CONSTRAINT "views_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "views" ADD CONSTRAINT "views_department_id_departments_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "views_brand_built_in_key" ON "views" USING btree ("brand_id","built_in",coalesce("department_id", '00000000-0000-0000-0000-000000000000'::uuid)) WHERE "views"."built_in" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "views_brand_owner_sort_idx" ON "views" USING btree ("brand_id","owner_id","sort_order");
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "views" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "views" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "views_tenant_select" ON "views" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "views_tenant_insert" ON "views" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "views_tenant_update" ON "views" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "views_tenant_delete" ON "views" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "views_owner_only" ON "views" AS RESTRICTIVE FOR ALL
  USING (owner_id IS NULL OR owner_id::text = current_setting('app.principal_id', true))
  WITH CHECK (owner_id IS NULL OR owner_id::text = current_setting('app.principal_id', true));
