CREATE TYPE "public"."mailbox_method" AS ENUM('imap', 'inbound_parse');--> statement-breakpoint
CREATE TYPE "public"."mailbox_security" AS ENUM('tls', 'starttls');--> statement-breakpoint
CREATE TYPE "public"."remote_image_policy" AS ENUM('block', 'proxy');--> statement-breakpoint
CREATE TABLE "inbound_parse_settings" (
	"brand_id" uuid PRIMARY KEY NOT NULL,
	"secret" text,
	"secret_updated_at" timestamp with time zone,
	"secret_updated_by" uuid,
	"last_request_provider" text,
	"last_request_at" timestamp with time zone,
	"last_request_outcome" text
);
--> statement-breakpoint
CREATE TABLE "mailboxes" (
	"id" uuid PRIMARY KEY NOT NULL,
	"brand_id" uuid NOT NULL,
	"address" text NOT NULL,
	"display_name" text NOT NULL,
	"department_id" uuid NOT NULL,
	"method" "mailbox_method" NOT NULL,
	"imap_host" text,
	"imap_port" integer,
	"imap_security" "mailbox_security",
	"imap_username" text,
	"imap_password" text,
	"imap_password_updated_at" timestamp with time zone,
	"imap_password_updated_by" uuid,
	"imap_folder" text DEFAULT 'INBOX' NOT NULL,
	"poll_interval_seconds" integer DEFAULT 60 NOT NULL,
	"imap_uid_validity" text,
	"imap_last_uid" bigint,
	"remote_images" "remote_image_policy" DEFAULT 'block' NOT NULL,
	"auth_failure_is_spam" boolean DEFAULT false NOT NULL,
	"automated_allowlist" text[] DEFAULT '{}'::text[] NOT NULL,
	"inbound_provider" text,
	"last_polled_at" timestamp with time zone,
	"last_success_at" timestamp with time zone,
	"last_received_at" timestamp with time zone,
	"last_error" text,
	"last_error_kind" text,
	"last_error_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "mailboxes_poll_interval_check" CHECK ("mailboxes"."poll_interval_seconds" IN (30, 60, 120, 300)),
	CONSTRAINT "mailboxes_imap_complete_check" CHECK ("mailboxes"."method" <> 'imap' OR ("mailboxes"."imap_host" IS NOT NULL AND "mailboxes"."imap_port" IS NOT NULL AND "mailboxes"."imap_security" IS NOT NULL AND "mailboxes"."imap_username" IS NOT NULL))
);
--> statement-breakpoint
ALTER TABLE "ticket_messages" ADD COLUMN "email" jsonb;--> statement-breakpoint
ALTER TABLE "inbound_parse_settings" ADD CONSTRAINT "inbound_parse_settings_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inbound_parse_settings" ADD CONSTRAINT "inbound_parse_settings_secret_updated_by_users_id_fk" FOREIGN KEY ("secret_updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mailboxes" ADD CONSTRAINT "mailboxes_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mailboxes" ADD CONSTRAINT "mailboxes_department_id_departments_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mailboxes" ADD CONSTRAINT "mailboxes_imap_password_updated_by_users_id_fk" FOREIGN KEY ("imap_password_updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "mailboxes_address_key" ON "mailboxes" USING btree ("address");--> statement-breakpoint
CREATE INDEX "mailboxes_brand_idx" ON "mailboxes" USING btree ("brand_id");
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "mailboxes" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "mailboxes" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "mailboxes_tenant_select" ON "mailboxes" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "mailboxes_tenant_insert" ON "mailboxes" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "mailboxes_tenant_update" ON "mailboxes" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "mailboxes_tenant_delete" ON "mailboxes" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
ALTER TABLE "inbound_parse_settings" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "inbound_parse_settings" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "inbound_parse_settings_tenant_select" ON "inbound_parse_settings" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "inbound_parse_settings_tenant_insert" ON "inbound_parse_settings" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "inbound_parse_settings_tenant_update" ON "inbound_parse_settings" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "inbound_parse_settings_tenant_delete" ON "inbound_parse_settings" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
