-- M3-06 and M3-08.
--
-- `canned_responses`: canned responses and macros in one table, told apart by
-- `kind`. Brand-scoped like every tenant table, plus the restrictive owner
-- policy `views` has (OWNER_SCOPED_TABLES in src/rls.ts), so a personal one is
-- its owner's alone.
--
-- `audit_log` gains where a request came from. The three columns default to the
-- `app.request_*` settings the api's tenant interceptor sets on every request
-- transaction, so every existing writer fills them without a change and a
-- worker's rows, which serve no request, are null. The new index is the
-- install-wide viewer's read: every brand's rows newest first, paged by
-- (created_at, id).
CREATE TYPE "public"."canned_response_kind" AS ENUM('canned', 'macro');--> statement-breakpoint
CREATE TABLE "canned_responses" (
	"id" uuid PRIMARY KEY NOT NULL,
	"brand_id" uuid NOT NULL,
	"owner_id" uuid,
	"department_id" uuid,
	"kind" "canned_response_kind" NOT NULL,
	"name" varchar(120) NOT NULL,
	"bodies" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"actions" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"last_used_at" timestamp with time zone,
	"updated_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "audit_log" ADD COLUMN "ip" "inet" DEFAULT nullif(current_setting('app.request_ip', true), '')::inet;--> statement-breakpoint
ALTER TABLE "audit_log" ADD COLUMN "request_id" text DEFAULT nullif(current_setting('app.request_id', true), '');--> statement-breakpoint
ALTER TABLE "audit_log" ADD COLUMN "user_agent" text DEFAULT nullif(current_setting('app.request_user_agent', true), '');--> statement-breakpoint
ALTER TABLE "canned_responses" ADD CONSTRAINT "canned_responses_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "canned_responses" ADD CONSTRAINT "canned_responses_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "canned_responses" ADD CONSTRAINT "canned_responses_department_id_departments_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "canned_responses_brand_owner_name_idx" ON "canned_responses" USING btree ("brand_id","owner_id","name");--> statement-breakpoint
CREATE INDEX "audit_log_created_at_id_idx" ON "audit_log" USING btree ("created_at","id");
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "canned_responses" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "canned_responses" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "canned_responses_tenant_select" ON "canned_responses" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "canned_responses_tenant_insert" ON "canned_responses" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "canned_responses_tenant_update" ON "canned_responses" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "canned_responses_tenant_delete" ON "canned_responses" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "canned_responses_owner_only" ON "canned_responses" AS RESTRICTIVE FOR ALL
  USING (owner_id IS NULL OR owner_id::text = current_setting('app.principal_id', true))
  WITH CHECK (owner_id IS NULL OR owner_id::text = current_setting('app.principal_id', true));
