-- M4-02, M4-03, M4-08: the chat widget. `widget_settings` (brand) holds a
-- brand's widget configuration and its encrypted signing secret;
-- `widget_visitors` (brand) holds each visitor's id and the sha256 of their
-- secret (DOMAIN-RULES §4.1); `tickets.visitor_id` is conversation ownership.
-- `email_delivery_kind` gains `transcript`, which is not an auto-reply, so
-- the one-per-ticket index is narrowed to the two auto-reply kinds.
ALTER TYPE "public"."email_delivery_kind" ADD VALUE 'transcript';--> statement-breakpoint
CREATE TABLE "widget_settings" (
	"brand_id" uuid PRIMARY KEY NOT NULL,
	"appearance" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"conversation" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"allowed_origins" text[] DEFAULT '{}'::text[] NOT NULL,
	"captcha_enabled" boolean DEFAULT false NOT NULL,
	"signed_identity_enabled" boolean DEFAULT false NOT NULL,
	"signed_identity_sees_all_channels" boolean DEFAULT false NOT NULL,
	"signing_secret" text,
	"signing_secret_set_at" timestamp with time zone,
	"signing_secret_set_by" uuid,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "widget_visitors" (
	"id" uuid PRIMARY KEY NOT NULL,
	"brand_id" uuid NOT NULL,
	"secret_hash" text NOT NULL,
	"contact_id" uuid,
	"verified_contact_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DROP INDEX "email_deliveries_auto_reply_key";--> statement-breakpoint
ALTER TABLE "tickets" ADD COLUMN "visitor_id" uuid;--> statement-breakpoint
ALTER TABLE "widget_settings" ADD CONSTRAINT "widget_settings_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "widget_settings" ADD CONSTRAINT "widget_settings_signing_secret_set_by_users_id_fk" FOREIGN KEY ("signing_secret_set_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "widget_visitors" ADD CONSTRAINT "widget_visitors_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "widget_visitors" ADD CONSTRAINT "widget_visitors_contact_id_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."contacts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "widget_visitors" ADD CONSTRAINT "widget_visitors_verified_contact_id_contacts_id_fk" FOREIGN KEY ("verified_contact_id") REFERENCES "public"."contacts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "widget_visitors_secret_hash_key" ON "widget_visitors" USING btree ("secret_hash");--> statement-breakpoint
CREATE INDEX "widget_visitors_brand_last_seen_idx" ON "widget_visitors" USING btree ("brand_id","last_seen_at");--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_visitor_id_widget_visitors_id_fk" FOREIGN KEY ("visitor_id") REFERENCES "public"."widget_visitors"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "tickets_visitor_idx" ON "tickets" USING btree ("visitor_id") WHERE "tickets"."visitor_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "email_deliveries_auto_reply_key" ON "email_deliveries" USING btree ("ticket_id","kind") WHERE "email_deliveries"."kind" in ('acknowledgment', 'out_of_hours');
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "widget_settings" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "widget_settings" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "widget_settings_tenant_select" ON "widget_settings" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "widget_settings_tenant_insert" ON "widget_settings" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "widget_settings_tenant_update" ON "widget_settings" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "widget_settings_tenant_delete" ON "widget_settings" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
ALTER TABLE "widget_visitors" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "widget_visitors" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "widget_visitors_tenant_select" ON "widget_visitors" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "widget_visitors_tenant_insert" ON "widget_visitors" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "widget_visitors_tenant_update" ON "widget_visitors" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "widget_visitors_tenant_delete" ON "widget_visitors" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
