-- M4-09: the hosted web form. `web_form_settings` is a brand's form (on/off,
-- department, CAPTCHA, thank-you message, field layout); `custom_field_defs.web_form`
-- is the "Show on web form" flag of a ticket custom field.

CREATE TABLE "web_form_settings" (
	"brand_id" uuid PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"department_id" uuid,
	"captcha_enabled" boolean DEFAULT false NOT NULL,
	"thank_you" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"fields" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"updated_by" uuid,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "custom_field_defs" ADD COLUMN "web_form" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "web_form_settings" ADD CONSTRAINT "web_form_settings_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "web_form_settings" ADD CONSTRAINT "web_form_settings_department_id_departments_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "web_form_settings" ADD CONSTRAINT "web_form_settings_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "web_form_settings" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "web_form_settings" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "web_form_settings_tenant_select" ON "web_form_settings" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "web_form_settings_tenant_insert" ON "web_form_settings" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "web_form_settings_tenant_update" ON "web_form_settings" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "web_form_settings_tenant_delete" ON "web_form_settings" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
