-- M8-04: the report rollups the `stats.rollup` job rebuilds per brand and
-- local day. The ticket rollups are department-scoped tenant tables, like the
-- tickets they summarise; the help center rollups are brand-scoped.
CREATE TABLE "report_agent_daily" (
	"brand_id" uuid NOT NULL,
	"day" date NOT NULL,
	"department_id" uuid NOT NULL,
	"channel" "ticket_channel" NOT NULL,
	"agent_id" uuid NOT NULL,
	"replies" integer DEFAULT 0 NOT NULL,
	"resolved" integer DEFAULT 0 NOT NULL,
	"assigned_open" integer DEFAULT 0 NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "report_daily" (
	"brand_id" uuid NOT NULL,
	"day" date NOT NULL,
	"department_id" uuid NOT NULL,
	"channel" "ticket_channel" NOT NULL,
	"priority" "ticket_priority" NOT NULL,
	"created" integer DEFAULT 0 NOT NULL,
	"resolved" integer DEFAULT 0 NOT NULL,
	"backlog" integer DEFAULT 0 NOT NULL,
	"first_response_ms" bigint[] DEFAULT '{}'::bigint[] NOT NULL,
	"resolution_ms" bigint[] DEFAULT '{}'::bigint[] NOT NULL,
	"sla_response_met" integer DEFAULT 0 NOT NULL,
	"sla_response_breached" integer DEFAULT 0 NOT NULL,
	"sla_resolution_met" integer DEFAULT 0 NOT NULL,
	"sla_resolution_breached" integer DEFAULT 0 NOT NULL,
	"csat_1" integer DEFAULT 0 NOT NULL,
	"csat_2" integer DEFAULT 0 NOT NULL,
	"csat_3" integer DEFAULT 0 NOT NULL,
	"csat_4" integer DEFAULT 0 NOT NULL,
	"csat_5" integer DEFAULT 0 NOT NULL,
	"created_by_hour" integer[] DEFAULT '{}'::integer[] NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "report_help_center_daily" (
	"brand_id" uuid NOT NULL,
	"day" date NOT NULL,
	"article_views" integer DEFAULT 0 NOT NULL,
	"widget_views" integer DEFAULT 0 NOT NULL,
	"widget_views_followed_by_ticket" integer DEFAULT 0 NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "report_search_daily" (
	"brand_id" uuid NOT NULL,
	"day" date NOT NULL,
	"locale" "locale" NOT NULL,
	"query" varchar(200) NOT NULL,
	"searches" integer DEFAULT 0 NOT NULL,
	"zero_results" integer DEFAULT 0 NOT NULL,
	"opened" integer DEFAULT 0 NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "report_agent_daily" ADD CONSTRAINT "report_agent_daily_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "report_daily" ADD CONSTRAINT "report_daily_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "report_help_center_daily" ADD CONSTRAINT "report_help_center_daily_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "report_search_daily" ADD CONSTRAINT "report_search_daily_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "report_agent_daily_brand_day_idx" ON "report_agent_daily" USING btree ("brand_id","day");--> statement-breakpoint
CREATE INDEX "report_daily_brand_day_idx" ON "report_daily" USING btree ("brand_id","day");--> statement-breakpoint
CREATE INDEX "report_help_center_daily_brand_day_idx" ON "report_help_center_daily" USING btree ("brand_id","day");--> statement-breakpoint
CREATE INDEX "report_search_daily_brand_day_idx" ON "report_search_daily" USING btree ("brand_id","day");
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "report_daily" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "report_daily" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "report_daily_tenant_select" ON "report_daily" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
CREATE POLICY "report_daily_tenant_insert" ON "report_daily" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
CREATE POLICY "report_daily_tenant_update" ON "report_daily" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
CREATE POLICY "report_daily_tenant_delete" ON "report_daily" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
ALTER TABLE "report_agent_daily" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "report_agent_daily" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "report_agent_daily_tenant_select" ON "report_agent_daily" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
CREATE POLICY "report_agent_daily_tenant_insert" ON "report_agent_daily" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
CREATE POLICY "report_agent_daily_tenant_update" ON "report_agent_daily" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
CREATE POLICY "report_agent_daily_tenant_delete" ON "report_agent_daily" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[])
    AND (coalesce(nullif(current_setting('app.all_departments', true), '')::boolean, false) OR department_id = ANY (nullif(current_setting('app.department_ids', true), '')::uuid[])));
--> statement-breakpoint
ALTER TABLE "report_search_daily" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "report_search_daily" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "report_search_daily_tenant_select" ON "report_search_daily" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "report_search_daily_tenant_insert" ON "report_search_daily" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "report_search_daily_tenant_update" ON "report_search_daily" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "report_search_daily_tenant_delete" ON "report_search_daily" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
ALTER TABLE "report_help_center_daily" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "report_help_center_daily" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "report_help_center_daily_tenant_select" ON "report_help_center_daily" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "report_help_center_daily_tenant_insert" ON "report_help_center_daily" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "report_help_center_daily_tenant_update" ON "report_help_center_daily" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "report_help_center_daily_tenant_delete" ON "report_help_center_daily" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
