-- M7-03: the sync schedule, progress and failure code of a knowledge source, its
-- per-line sync log, and one help center source per brand.

CREATE TYPE "public"."knowledge_log_level" AS ENUM('info', 'warn', 'error', 'done');--> statement-breakpoint
CREATE TYPE "public"."knowledge_sync_schedule" AS ENUM('automatic', 'daily', 'weekly', 'manual');--> statement-breakpoint
CREATE TABLE "knowledge_sync_log" (
	"id" uuid PRIMARY KEY NOT NULL,
	"brand_id" uuid NOT NULL,
	"source_id" uuid NOT NULL,
	"run_id" uuid NOT NULL,
	"level" "knowledge_log_level" NOT NULL,
	"code" text NOT NULL,
	"params" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "knowledge_sources" ADD COLUMN "schedule" "knowledge_sync_schedule" DEFAULT 'manual' NOT NULL;--> statement-breakpoint
ALTER TABLE "knowledge_sources" ADD COLUMN "sync_started_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "knowledge_sources" ADD COLUMN "progress_done" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "knowledge_sources" ADD COLUMN "progress_total" integer;--> statement-breakpoint
ALTER TABLE "knowledge_sources" ADD COLUMN "last_error_code" text;--> statement-breakpoint
ALTER TABLE "knowledge_sources" ADD COLUMN "created_by" text;--> statement-breakpoint
ALTER TABLE "knowledge_sync_log" ADD CONSTRAINT "knowledge_sync_log_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "knowledge_sync_log" ADD CONSTRAINT "knowledge_sync_log_source_id_knowledge_sources_id_fk" FOREIGN KEY ("source_id") REFERENCES "public"."knowledge_sources"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "knowledge_sync_log_source_idx" ON "knowledge_sync_log" USING btree ("source_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "knowledge_sources_article_key" ON "knowledge_sources" USING btree ("brand_id") WHERE "knowledge_sources"."kind" = 'article';
--> statement-breakpoint
-- Generated by `pnpm --filter @helpdock/db gen:rls` from TENANT_TABLES in src/rls.ts.
-- Edit that list and regenerate; do not edit this file by hand.
--
-- Every tenant table of DOMAIN-RULES §1.3: row-level security enabled, forced so
-- the owner is bound by it too, and one policy per command reading the
-- `app.*` settings the request transaction sets.
ALTER TABLE "knowledge_sync_log" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "knowledge_sync_log" FORCE ROW LEVEL SECURITY;
--> statement-breakpoint
CREATE POLICY "knowledge_sync_log_tenant_select" ON "knowledge_sync_log" FOR SELECT
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "knowledge_sync_log_tenant_insert" ON "knowledge_sync_log" FOR INSERT
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "knowledge_sync_log_tenant_update" ON "knowledge_sync_log" FOR UPDATE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]))
  WITH CHECK (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
--> statement-breakpoint
CREATE POLICY "knowledge_sync_log_tenant_delete" ON "knowledge_sync_log" FOR DELETE
  USING (brand_id = ANY (nullif(current_setting('app.brand_ids', true), '')::uuid[]));
