import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { uuidv7 } from '../uuid.js';
import { brands } from './brands.js';
import { contacts } from './contacts.js';
import { departments } from './departments.js';
import { telegramDeliveryStatusEnum } from './enums.js';
import { ticketMessages } from './ticket-messages.js';
import { tickets } from './tickets.js';
import { users } from './users.js';

/**
 * A Telegram bot a brand answers through (M6-01, M6-05). A brand may have
 * several; each files new conversations into its own department.
 *
 * **`telegram_id` is unique across the install**, as `mailboxes.address` is:
 * the webhook names a bot, and one bot answering for two brands would make
 * which brand a chat belongs to a guess.
 *
 * **`token` and `webhook_secret` are secrets**: the `v1.<keyId>.…` envelope
 * `@helpdock/config` writes under `APP_MASTER_KEY`, never returned to a client
 * after they are saved (REQUIREMENTS §5.1). The webhook secret is the
 * `X-Telegram-Bot-Api-Secret-Token` Telegram sends back with every update.
 *
 * Brand-scoped and not department-scoped: a bot is configuration, like a
 * mailbox.
 */
export const telegramBots = pgTable(
  'telegram_bots',
  {
    id: uuid('id')
      .primaryKey()
      .$defaultFn(() => uuidv7()),
    brandId: uuid('brand_id')
      .notNull()
      .references(() => brands.id, { onDelete: 'cascade' }),
    /** The bot's own user id, from `getMe`. */
    telegramId: bigint('telegram_id', { mode: 'number' }).notNull(),
    /** `@acme_support_bot`, without the `@`, from `getMe`. */
    username: text('username').notNull(),
    displayName: text('display_name').notNull(),
    /** Where a new conversation is filed. Replies stay where their ticket is. */
    departmentId: uuid('department_id')
      .notNull()
      .references(() => departments.id, { onDelete: 'restrict' }),
    /** Encrypted. */
    token: text('token').notNull(),
    tokenUpdatedAt: timestamp('token_updated_at', { withTimezone: true }).notNull(),
    tokenUpdatedBy: uuid('token_updated_by').references(() => users.id, { onDelete: 'set null' }),
    /** Encrypted. Generated by Helpdock, never typed. */
    webhookSecret: text('webhook_secret').notNull(),
    /** M6-04: the `/start` reply, per language. Null is the catalog's default. */
    welcomeEn: text('welcome_en'),
    welcomeAr: text('welcome_ar'),
    /**
     * M6-04: the question `/start` asks before the contact's language is known,
     * one text that names both languages. Null is the catalog's default.
     */
    languagePrompt: text('language_prompt'),
    /** M6-04: whether `/start` offers English / العربية. */
    languagePick: boolean('language_pick').notNull().default(true),
    /** The URL the last "Set webhook" registered, and when. */
    webhookUrl: text('webhook_url'),
    webhookSetAt: timestamp('webhook_set_at', { withTimezone: true }),
    /** The long-polling cursor (development): the next `getUpdates` offset. */
    pollOffset: bigint('poll_offset', { mode: 'number' }),
    lastUpdateAt: timestamp('last_update_at', { withTimezone: true }),
    /** What Telegram or the pipeline said the last time it failed. Never the token. */
    lastError: text('last_error'),
    lastErrorAt: timestamp('last_error_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('telegram_bots_telegram_id_key').on(table.telegramId),
    index('telegram_bots_brand_idx').on(table.brandId),
  ],
);

export type TelegramBot = typeof telegramBots.$inferSelect;
export type NewTelegramBot = typeof telegramBots.$inferInsert;

/**
 * One private chat with one bot (M6-02): `chat_id` is the contact's identity
 * (DOMAIN-RULES §4.4, verified because it comes from the Bot API) and
 * `ticket_id` is the conversation the next message continues, so a chat has
 * one open ticket at a time.
 *
 * Brand-scoped: it names a ticket but holds none of it, as `notifications`
 * does, and a ticket's own policy decides who may read the ticket.
 */
export const telegramChats = pgTable(
  'telegram_chats',
  {
    id: uuid('id')
      .primaryKey()
      .$defaultFn(() => uuidv7()),
    brandId: uuid('brand_id')
      .notNull()
      .references(() => brands.id, { onDelete: 'cascade' }),
    botId: uuid('bot_id')
      .notNull()
      .references(() => telegramBots.id, { onDelete: 'cascade' }),
    /** Telegram's chat id, as text: it can exceed 2^53 in principle and is only compared. */
    chatId: text('chat_id').notNull(),
    contactId: uuid('contact_id')
      .notNull()
      .references(() => contacts.id, { onDelete: 'cascade' }),
    ticketId: uuid('ticket_id').references(() => tickets.id, { onDelete: 'set null' }),
    /** The customer's `@username`, without the `@`, as of their last message. It can change. */
    username: text('username'),
    /** M6-04: when the customer pressed a language button. Null: the language was inferred. */
    languageChosenAt: timestamp('language_chosen_at', { withTimezone: true }),
    lastMessageAt: timestamp('last_message_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('telegram_chats_bot_chat_key').on(table.botId, table.chatId),
    index('telegram_chats_brand_contact_idx').on(table.brandId, table.contactId),
    index('telegram_chats_ticket_idx').on(table.ticketId),
  ],
);

export type TelegramChat = typeof telegramChats.$inferSelect;

/**
 * One agent reply to deliver to a chat (M6-02), the Telegram twin of
 * `email_deliveries`: written beside the `telegram.reply` outbox row in the
 * reply's transaction, moved along by the `telegram.send` job, and the place a
 * failure is recorded.
 *
 * **The chat is frozen at creation**, so a retry delivers to the chat the
 * reply was written for. **Department-scoped**, as every child of a ticket is.
 * The body is the ticket message's, rendered when sent.
 */
export const telegramDeliveries = pgTable(
  'telegram_deliveries',
  {
    id: uuid('id')
      .primaryKey()
      .$defaultFn(() => uuidv7()),
    brandId: uuid('brand_id')
      .notNull()
      .references(() => brands.id, { onDelete: 'cascade' }),
    /** Overwritten by the trigger with the ticket's own. */
    departmentId: uuid('department_id')
      .notNull()
      .references(() => departments.id, { onDelete: 'restrict' }),
    ticketId: uuid('ticket_id')
      .notNull()
      .references(() => tickets.id, { onDelete: 'cascade' }),
    ticketMessageId: uuid('ticket_message_id')
      .notNull()
      .references(() => ticketMessages.id, { onDelete: 'cascade' }),
    botId: uuid('bot_id')
      .notNull()
      .references(() => telegramBots.id, { onDelete: 'cascade' }),
    chatId: text('chat_id').notNull(),
    status: telegramDeliveryStatusEnum('status').notNull().default('queued'),
    /**
     * How many parts of the message Telegram has accepted. A long reply is
     * several `sendMessage` calls; a retry starts after the last one that
     * landed, so the customer never reads a part twice.
     */
    partsSent: integer('parts_sent').notNull().default(0),
    /** Telegram's ids for what was sent, in order. */
    sentMessageIds: text('sent_message_ids').array().notNull().default(sql`'{}'::text[]`),
    attempts: integer('attempts').notNull().default(0),
    /** Telegram's last refusal, truncated. Never the token. */
    lastError: text('last_error'),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    failedAt: timestamp('failed_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    uniqueIndex('telegram_deliveries_message_key').on(table.ticketMessageId),
    index('telegram_deliveries_ticket_idx').on(table.ticketId),
    index('telegram_deliveries_brand_status_idx').on(table.brandId, table.status),
  ],
);

export type TelegramDelivery = typeof telegramDeliveries.$inferSelect;
export type NewTelegramDelivery = typeof telegramDeliveries.$inferInsert;
